# Generated by Django 5.0.4 on 2024-04-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPost',
        ),
        migrations.DeleteModel(
            name='FavoritePost',
        ),
        migrations.DeleteModel(
            name='FollowMyUser',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
