# Generated by Django 5.0.2 on 2024-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
