# Generated by Django 5.0.2 on 2024-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_telegram_comments_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_visiable',
            field=models.BooleanField(default=True),
        ),
    ]
