# Generated by Django 5.0.2 on 2024-03-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact_created_at_contact_is_responded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
