# Generated by Django 5.0.2 on 2024-02-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Articles',
        ),
    ]
