# Generated by Django 5.0.2 on 2024-02-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_created_at_articles_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
