# Generated by Django 5.0.2 on 2024-03-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments_telegram_comments_email_comments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Telegram',
            new_name='telegram',
        ),
    ]
