# Generated by Django 5.0.2 on 2024-02-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='main_page',
            field=models.BooleanField(default=True),
        ),
    ]
