# Generated by Django 5.0.2 on 2024-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contactus_created_at_contactus_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_responsed',
            field=models.BooleanField(default=False),
        ),
    ]
