# Generated by Django 5.0.2 on 2024-02-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article_id',
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.articles'),
            preserve_default=False,
        ),
    ]
