# Generated by Django 5.0.3 on 2024-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentpost_created_at_commentpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='media/user/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='media/post/'),
        ),
    ]
