# Generated by Django 5.0.3 on 2024-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_myuser_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='write_comment',
            field=models.BooleanField(default=True),
        ),
    ]
