# Generated by Django 5.0.3 on 2024-03-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_write_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disable_btn_title',
            field=models.TextField(default='Disable', max_length=15),
        ),
    ]
