# Generated by Django 5.0.4 on 2024-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
