# Generated by Django 5.0.2 on 2024-02-22 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='creator_image',
            field=models.CharField(default=django.utils.timezone.now, max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_title_image',
            field=models.CharField(max_length=4000),
        ),
    ]
