# Generated by Django 5.0.2 on 2024-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_creator_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_title_image',
            field=models.ImageField(upload_to='posts/image/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='creator_image',
            field=models.ImageField(upload_to='users/image/'),
        ),
    ]
