# Generated by Django 5.0.2 on 2024-03-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_articles_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='view_count',
            field=models.IntegerField(),
        ),
    ]
